### ISSUE TITLE
lxde hangs on sign in [overo]

### ISSUE THREAD

**Issue by elleryrussell** [gumstix/live-build#3]
Followed the stock directions for making the lxde vivid image for overo.
On boot, I get to the login screen and try to sign in as gumstix, the screen flashes for a second and then goes to the blank desktop (the normal lxde background) with a movable cursor.  None of the mouse actions prompt anything, and none of the desktop elements ever load. If I try to login with openbox instead of lubuntu, I can at least get right click actions to work, which will bring up a terminal or browser, but it's prone to crashing.

**Comment by arunbharadwaj** [comment]
Hi,

I tried replicating this on my setup here. Lubuntu has always been unstable with live-build and we are looking at ways to improve this. With respect to openbox, I didn't seem to have any issues, logging in and playing around with the desktop environment. Could you be a little more specific about your setup so that I can try and replicate it here. Also, if you could post any related debug console messages, that would be useful.

**Comment by yangjiel** [comment]
Close for no response, if you have further question please open this again, thanks.
